service: start-war

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  main:
    handler: dist/main.bootstrap
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    environment:
      STAGE: prod
      SYNCRONIZE: false
      MYSQL_SERVICE: mysql
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: starwar
      BACKEND_PORT: 3000
      SWAPI_URL: https://swapi.py4e.com/api

custom:
  webpack:
    webpackConfig: './webpack.config.js'

package:
  exclude:
    - node_modules/**
